apiVersion: batch/v1
kind: Job
metadata:
  name: rheem-pagerank-soc-job
spec:
  template: 
    spec: 
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvc-nfs
      containers:
        - name: rheem-pagerank-soc
          image: spark-env:v0
          imagePullPolicy: IfNotPresent
          command: ["java"]
          args:  ["-jar", "/data/lfy/jars/pagerank_soc.jar", "basic-graph,java,java-conversion,java-graph,graphchi", "file:/data/datasets/pagerank_soc_LiveJournal.txt", "15",  "/data/lfy/results/pagerank_result.txt"]
          volumeMounts:
            - mountPath: /data
              name: nfs-volume
      restartPolicy: Never